[package]
name = "rust-challenge-1"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.6.0", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
wincode = { version = "0.3.1", features = ["derive"] }
